Updating SDK
CleverPet/spark-setup-android pull request #1
Opened 2017-03-15 22:19 UTC by sismanis

Smoke tested with setting this as the new local maven repo

2017-03-17 19:02 UTC, philipmeier requested changes
I am cool with these changes, after answering Qs and confirming that the build is reproducible on another laptop.  I think that maybe on Monday, Csaba and I should sit down with you and confirm that we can build.   I suspect most of this will be you helping us out with standard setup, and then the last bit is confirming the maven dependencies work the same.

2017-03-17 19:02 UTC, philipmeier commented on devicesetup/devicesetup.iml
> +    <orderEntry type="jdk" jdkName="Android API 25 Platform (1)" jdkType="Android SDK" />
whats the "(1)" ?

2017-03-17 19:02 UTC, philipmeier commented on devicesetup/devicesetup.iml
> +      <sourceFolder url="file://$MODULE_DIR$/src/test/shaders" isTestSource="true" />
what are all of these "shaders" changes?

2017-03-17 19:02 UTC, philipmeier commented on devicesetup/devicesetup.iml
> +      <sourceFolder url="file://$MODULE_DIR$/src/test/shaders" isTestSource="true" />
i suspect the is openGL stuff.  Is this the consequence of 23-->25, and how did it get here?

2017-03-20 20:05 UTC, sismanis commented
I will be in later today to help you guys get it compiling. These changes were auto-generated when I upgraded the gradle file. There might be an argument for including this file in .gitignore. Not 100% sure on that though. We can discuss today while I am in.

2017-04-26 20:13 UTC, closed without merging